# K-Means

In [1]:
import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
c:\Users\Greesha Vaishnavi\Desktop\dsprojects\E_Commerce_Customer_Segmentation\research

In [2]:
# IMPORT REQUIRED LIBRARIES

import pandas as pd
import numpy as np

In [3]:
# LOAD TRANSFORMED DATA

rfm = pd.read_csv("../artifacts/data_transformation/customer_rfm.csv")

rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

In [4]:
# VERIFY TRANSFORMED DATA

print("Shape:", rfm.shape)

print("\nColumns:")
print(rfm.columns.tolist())

print("\nData Types:")
print(rfm.dtypes)

print("\nMissing Values:")
print(rfm.isnull().sum())

Shape: (4338, 4)

Columns:
['CustomerID', 'Recency', 'Frequency', 'Monetary']

Data Types:
CustomerID    float64
Recency         int64
Frequency       int64
Monetary      float64
dtype: object

Missing Values:
CustomerID    0
Recency       0
Frequency     0
Monetary      0
dtype: int64

In [5]:
# VIEW TRANSFORMED RFM DATA

rfm.head(10)

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40
5     12352.0       36          8   2506.04
6     12353.0      204          1     89.00
7     12354.0      232          1   1079.40
8     12355.0      214          1    459.40
9     12356.0       23          3   2811.43

In [6]:
# SEPARATE CUSTOMER ID AND FEATURES

customer_ids = rfm["CustomerID"]

X = rfm[["Recency", "Frequency", "Monetary"]]

print("Customer IDs shape:", customer_ids.shape)
print("Feature shape:", X.shape)

Customer IDs shape: (4338,)
Feature shape: (4338, 3)

In [7]:
# Check skewness

X.skew()

Recency       1.246048
Frequency    12.067031
Monetary     19.339368
dtype: float64

In [8]:
# Log transform RFM features

X_log = np.log1p(X)   # To reduce skewness and compress extreme values

X_log.head()

    Recency  Frequency   Monetary
0  5.789960   0.693147  11.253955
1  1.098612   2.079442   8.368925
2  4.330733   1.609438   7.494564
3  2.995732   0.693147   7.472245
4  5.739793   0.693147   5.815324

In [9]:
# Check skewness after log transformation

X_log.skew()    # skewness to become less extreme

Recency     -0.379169
Frequency    1.208652
Monetary     0.396599
dtype: float64

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
# Scale transformed features

scaler = StandardScaler()  #To put the features on a comparable scale because K-Means is distance-based

X_scaled = scaler.fit_transform(X_log)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X_log.columns,
    index=X_log.index
)

X_scaled.head()

    Recency  Frequency  Monetary
0  1.461993  -0.955214  3.707716
1 -2.038734   1.074425  1.414903
2  0.373104   0.386304  0.720024
3 -0.623086  -0.955214  0.702287
4  1.424558  -0.955214 -0.614514

In [12]:
# Check scaled data

print(X_scaled.mean())
print(X_scaled.std())

Recency     -8.025955e-17
Frequency   -8.189750e-18
Monetary    -3.734526e-16
dtype: float64
Recency      1.000115
Frequency    1.000115
Monetary     1.000115
dtype: float64

# Baseline Model

In [13]:
from sklearn.cluster import KMeans

In [ ]:
inertia = []         #We'll store the inertia for every K

for k in range(2, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    
    kmeans.fit(X_scaled)
    
    inertia.append(kmeans.inertia_)   #Inertia naturally decreases as K increases