# Hierarchical Clustering

In [1]:
# Import libraries

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Check current working directory

print(os.getcwd())

c:\Users\Greesha Vaishnavi\Desktop\dsprojects\E_Commerce_Customer_Segmentation\research

In [3]:
# Load transformed data

rfm = pd.read_csv("../artifacts/data_transformation/customer_rfm.csv")

rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

In [4]:
# Check data shape

print("Shape:", rfm.shape)

Shape: (4338, 4)

In [5]:
# Check columns

print("Columns:", rfm.columns.tolist())

Columns: ['CustomerID', 'Recency', 'Frequency', 'Monetary']

In [6]:
# Check missing values

print(rfm.isnull().sum())

CustomerID    0
Recency       0
Frequency     0
Monetary      0
dtype: int64

In [7]:
# Separate customer ID and features

customer_ids = rfm["CustomerID"]

X = rfm[["Recency", "Frequency", "Monetary"]]

print("Customer IDs shape:", customer_ids.shape)
print("Features shape:", X.shape)

Customer IDs shape: (4338,)
Features shape: (4338, 3)

# Data Preprocessing

In [8]:
# Check skewness

print(X.skew())

Recency       1.246048
Frequency    12.067031
Monetary     19.339368
dtype: float64

In [9]:
# Apply log transformation

X_log = np.log1p(X)

X_log.head()

    Recency  Frequency   Monetary
0  5.789960   0.693147  11.253955
1  1.098612   2.079442   8.368925
2  4.330733   1.609438   7.494564
3  2.995732   0.693147   7.472245
4  5.739793   0.693147   5.815324

In [10]:
# Check skewness after log transformation

print(X_log.skew())

Recency     -0.379169
Frequency    1.208652
Monetary     0.396599
dtype: float64